version: '3'

services:
  meetup12ru-db:
    image: "postgres:11-alpine"
    container_name: meetup12ru-db
    volumes:
      - "$PWD/var/postgres_files:/var/lib/postgresql/data"
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
    user: "$USER_ID"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: meetup12ru
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: meetup12ru

  meetup12ru-test-db:
    image: "postgres:11-alpine"
    container_name: meetup12ru-test-db
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: meetup12ru
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: meetup12ru

  meetup12ru:
    image: "sshambir/meetup12ru:master"
    container_name: meetup12ru
    volumes:
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
    user: "$USER_ID"
    ports:
      - "80:3000"
    depends_on:
      - meetup12ru-db
    environment:
      NODE_ENV: "dev"
      SITE_PORT_HTTP: "3000"
      SITE_DSN: "postgres://meetup12ru:1234@meetup12ru-db/meetup12ru"
      SITE_SESSION_SECRET: "amqg7i0Q"
      SITE_CONFIG: "/app/config/meetup12ru.json"
